name: hdbrent-environment
channels:
  - conda-forge
dependencies:
  - numpy
  - pandas
  - panel
  - matplotlib
  - nbserverproxy
  - pyviz::param=1.9.0
  - pyviz::pyviz_comms=0.7.2
  - pyviz::datashader
  - bokeh::bokeh
  - pyviz::panel=0.5.1
  - tornado<6  
