name: hdbrent-environment
channels:
  - conda-forge
dependencies:
  - numpy
  - pandas
  - panel
  - ipywidgets
  - matplotlib
  - pyviz::param
  - pyviz::pyviz_comms
  - pyviz::datashader
  - bokeh::bokeh
  - pyviz::panel
  - tornado<6 
  - pip:
    - jupyter-server-proxy
    - nbserverproxy
commands:
  dashboard:
    unix: panel serve hdbRent.ipynb
    supports_http_options: true
  notebook:
    notebook: hdbRent.ipynb
