name: hdbrent-environment
channels:
  - conda-forge
dependencies:
  - numpy
  - pandas
  - panel
  - matplotlib
  - nbserverproxy
  - pyviz::param
  - pyviz::pyviz_comms
  - pyviz::datashader
  - bokeh::bokeh
  - pyviz::panel
  - tornado<6  
